// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClNl3qDJiBPh_qRPQvhAIrof9dI0-XM7A',
    appId: '1:150381440101:web:4638ef545e91f1c1116a8c',
    messagingSenderId: '150381440101',
    projectId: 'attendance-punch-30610',
    authDomain: 'attendance-punch-30610.firebaseapp.com',
    storageBucket: 'attendance-punch-30610.firebasestorage.app',
    measurementId: 'G-S674JDZHZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRNjwDFModif6s4Sf8sxKBdR83mjcb0aw',
    appId: '1:150381440101:android:32595c0cd1eddfe4116a8c',
    messagingSenderId: '150381440101',
    projectId: 'attendance-punch-30610',
    storageBucket: 'attendance-punch-30610.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLLywwIldQQtHhj6wOIYLFVQuKZCLSELc',
    appId: '1:150381440101:ios:18c522f263fe2e3b116a8c',
    messagingSenderId: '150381440101',
    projectId: 'attendance-punch-30610',
    storageBucket: 'attendance-punch-30610.firebasestorage.app',
    iosBundleId: 'com.example.attendancePunch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClNl3qDJiBPh_qRPQvhAIrof9dI0-XM7A',
    appId: '1:150381440101:web:763620bfde74d051116a8c',
    messagingSenderId: '150381440101',
    projectId: 'attendance-punch-30610',
    authDomain: 'attendance-punch-30610.firebaseapp.com',
    storageBucket: 'attendance-punch-30610.firebasestorage.app',
    measurementId: 'G-Z5JB8YWG5D',
  );
}
